apiVersion: v1
kind: Pod
metadata:
  name: samridh-test1
  labels: 
    env: beta
spec:
  containers:
  - image: samridhrakesh/cherrypy
    name: samridhr
    ports:
    - containerPort: 8080
      protocol: TCP
